/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutDialog.java
 *
 * Created on Mar 22, 2012, 1:14:49 AM
 */
package aplikasi.deteksi.plagiarisme.pkg3;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Sesha
 */
public class AboutDialog extends javax.swing.JDialog {

    /** Creates new form AboutDialog */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension framesize = getSize();
        setLocation((screenSize.width - framesize.width)/2, (screenSize.height - framesize.height)/2);
    }
    
    public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelJudul = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonClose = new javax.swing.JButton();
        LabelSkripsi = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        LabelNIM = new javax.swing.JLabel();
        LabelFakultas = new javax.swing.JLabel();
        LabelUniversitas = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bantuan: Tentang");

        LabelJudul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelJudul.setText("APLIKASI DETEKSI PLAGIARISME DOKUMEN TEKS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("DENGAN MENGGUNAKAN ALGORITMA RABIN KARP");

        ButtonClose.setText("Close");
        ButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close(evt);
            }
        });

        LabelSkripsi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelSkripsi.setText("SKRIPSI");

        LabelNama.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelNama.setText("Tia Septiana Widi");

        LabelNIM.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelNIM.setText("(20080810372)");

        LabelFakultas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelFakultas.setText("FAKULTAS ILMU KOMPUTER");

        LabelUniversitas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelUniversitas.setText("UNIVERSITAS KUNINGAN");

        LabelEmail.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        LabelEmail.setText("tia_aank@yahoo.co.id");

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Multimedia\\Picture\\Glyph + Icon\\Glypth 3D\\Document-Word.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelEmail)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelNIM))
                    .addComponent(LabelFakultas)
                    .addComponent(LabelUniversitas)
                    .addComponent(LabelSkripsi)
                    .addComponent(LabelJudul)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ButtonClose)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LabelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelSkripsi)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNama)
                            .addComponent(LabelNIM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelEmail)
                        .addGap(18, 18, 18)
                        .addComponent(LabelFakultas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelUniversitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void close(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close
// TODO add your handling code here:
    closeAboutBox();
}//GEN-LAST:event_close

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClose;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelFakultas;
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JLabel LabelNIM;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelSkripsi;
    private javax.swing.JLabel LabelUniversitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
