/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HowToDialog.java
 *
 * Created on May 3, 2012, 10:25:44 AM
 */
package aplikasi.deteksi.plagiarisme.pkg3;

import java.awt.Toolkit;

/**
 *
 * @author Sesha
 */
public class HowToDialog extends javax.swing.JDialog {

    /** Creates new form HowToDialog */
    public HowToDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        java.awt.Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension framesize = getSize();
        setLocation((screenSize.width - framesize.width)/2, (screenSize.height - framesize.height)/2);
    }
    public void closeHowToDialog() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bantuan: Cara Penggunaan");

        ButtonClose.setText("Close");
        ButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText("Memulai Proses Pendeteksian :\n - Masukan dokumen asli dan dokumen uji dengan megklik tombol \n   Cari untuk masing-masing dokumen\n - Pilih nilai K-gram yang akan digunakan dalam membandingan.\n - Untuk memulai proses penyamaan klik tombol Start.\n - Hasil pendeteksian akan tampil di sebelah kanan terdiri dari :\n   * Kgram (merupakan nilai K-gram yang digunakan)\n   * Jum. Pattern Sama (Jumlah pattern yang sama dari dua \n     dokumen)\n   * Persentasi Kemiripan (Nilai persentasi kemiripan dari dua \n     dokumen)\n   * Waktu proses (Waktu yang dibutuhkan dalam membandingkan isi dari \n     kedua dokumen)\n - Informasi Dokumen adalah informasi dari dokuemn Asli dan \n   Dokumen Uji yang dimasukan, terdiri dari :\n   * Nama dokumen, merupakan nama dokumen yang dimasukan.\n   * Jum. Kata sebeleum di proses, adalah jumlah kata yang ada \n     di dalam dokumen.\n   * Jum. Kata setelah di proses, adalah jumlah kata yang ada \n     setelah dilakukan proses stemming, yaitu proses pemotongan \n     sehingga didapat kata-kata dasar dari isi dokumen.\n   * Jum. Pattern, adalah jumlah pattern dari isi dokumen \n     berdasarkan nilai K-gram yang dipilih.\n - Highligh Pattern, merupakan highlight dari isi dokuemn, \n   setiap pattern yang sama akan diberi warna merah.\n\nMenyimpan hasil Pendeteksian :\n Untuk menyimpan hasil pendeteksian, pilih Menu File kemudian \n pilih submenu Simpan. Hasil proses pendeteksian akan disimpan ke dalam \n file pdf.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addComponent(ButtonClose))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void close(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close
// TODO add your handling code here:
    closeHowToDialog();
}//GEN-LAST:event_close

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
